### ISSUE TITLE
View enchanment

### ISSUE THREAD

**Issue by Arvindiyer** [Team-ISTE/fusion-16web-app#3]
- Index page text of click here is not so cool keep a button or something else but not so long text.
- Add colors to text in event modal .(Make it color full)
- Add the countdown timer anywhere in home page
- Check the links of footer and change google+ icon to a mail icon and mail id to our web.fusion mail id.
- Add the links of  facebook page of all committees in footer section along the side of google maps.

**Comment by Arvindiyer** [comment]
@Rohitpa7824  @vattytrivedi @maunilswadas 
- Countdown time work added and pushed to the branch.

**Comment by Arvindiyer** [comment]
@Rohitpa7824 @vattytrivedi @maunilswadas
- Add colors to text in event modal .(Make it color full) is only left. Do complete this if u feel so.

**Comment by Rohitpa7824** [comment]
added color to event modals and added gmail links.
